spring:
  application:
    name: MyMall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mymall?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080